name: intheshell.page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Generate html files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folders
        run: mkdir -p static/{atividades,sobre,wiki,writeups}

      - name: Copy public contents
        run: npm install pug-cli --global

      - name: Copy public contents
        run: cp -r site/public/* static

      - name: Generate html (index and error)
        run: pug -P site/views/{index,error}.pug -o static

      - name: Generate html (atividades)
        run: pug -P site/views/atividades -o static/atividades

      - name: Generate html (writeups)
        run: pug -P site/views/writeups -o static/writeups

      - name: Generate html (sobre)
        run: pug -P site/views/sobre -o static/sobre

      - name: Generate html (wiki)
        run: pug -P site/views/wiki -o static/wiki

      - name: Fix href
        run: |
            files_search=$(find static -name '*.html')
            files_sub=$(echo "$files_search" | sed -e 's/static\///g' -e 's/\.html//g' -e 's/[\.*^$[\/]/\\&/g')
            for f1 in $files_sub; do
                for f2 in $files_search; do
                    sed -i "s/href=\"\/$f1\"/href=\"\/$f1.html\"/g" "$f2"
                done
            done

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './static'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
